name: Sync Container Images to ACR

on:
  push:
    branches:
      - master

jobs:
  sync-images:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.cn-beijing.aliyuncs.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install skopeo
        run: sudo apt-get install -y skopeo

      - name: Login to ACR
        run: skopeo login $REGISTRY -u "${{ secrets.ACR_USERNAME }}" -p "${{ secrets.ACR_PASSWORD }}"

      - name: Sync Images
        run: |
          skopeo copy --all docker://docker.io/library/ubuntu:latest docker://$REGISTRY/cn-base/ubuntu:latest
          skopeo copy --all docker://docker.io/library/debian:latest docker://$REGISTRY/cn-base/debian:latest

          #skopeo copy --all docker://docker.io/library/nginx:latest docker://$REGISTRY/cn-infra/nginx:latest
          #skopeo copy --all docker://docker.io/library/redis:latest docker://$REGISTRY/cn-infra/redis:latest
          #skopeo copy --all docker://docker.io/library/postgres:latest docker://$REGISTRY/cn-infra/postgres:latest
          #skopeo copy --all docker://docker.io/library/mysql:latest docker://$REGISTRY/cn-infra/mysql:latest
          #skopeo copy --all docker://docker.io/library/zookeeper:latest docker://$REGISTRY/cn-infra/zookeeper:latest
          #skopeo copy --all docker://docker.io/library/flink:latest docker://$REGISTRY/cn-infra/flink:latest
          #skopeo copy --all docker://docker.io/library/spark:latest docker://$REGISTRY/cn-infra/spark:latest
          #skopeo copy --all docker://docker.io/library/clickhouse:latest docker://$REGISTRY/cn-infra/clickhouse:latest
